feat: add creation of rule files for ACT-TF
act-rules/act-rules-web pull request #200
Opened 2020-08-06 16:22 UTC by WilcoFiers

2020-10-13 11:53 UTC, jeeyyy commented on build/__test-utils.js
> +	const title = term[0].toUpperCase() + term.substr(1)
it would be good to safeguard against an undefined term

2020-10-13 12:23 UTC, jeeyyy requested changes
Some inline comments. Nice one @WilcoFiers. Good test coverage too 👍

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-markdown.js
> +		if (ruleIds.length && !ruleIds.includes(ruleData.frontmatter.id)) {
I see what you are doing here, but this would read better if rulesData was filtered to have only the ruleId's before the for loop, in my opinion.

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-rule-page/__tests__/get-acknowledgements.js
> +const outdent = require('outdent').default
Did not know `outdent` was a thing. Have learnt something new.

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-rule-page/get-rule-metadata.js
> +	const indentedLines = lines.map((line, index) => (index === 0 ? `:   ${line}` : `    ${line}`))
The number of spaces here seem different & hard to read. Worth using a library like [`indent-string`](https://www.npmjs.com/package/indent-string)

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-rule-page/get-rule-metadata.js
> +		'Last Modified:\n' + toDfnTerm('TODO (format Sep 25, 2019)'),
Was a todo here intentional?

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-rule-page/get-reference-links.js
> +	const firstDfn = markdownAST.children.find(({ type }) => type === 'definition')
Rather than walking the mdast yourself, I would recomment using [`visit`](https://www.npmjs.com/package/unist-util-visit).

There is also a helper utility function for this [`getMarkdownAstNodesOfType`](https://github.com/act-rules/act-rules-web/blob/c2e0f3442193095d27efca78d880fe08d7909361/utils/get-markdown-ast-nodes-of-type.js)

2020-10-13 12:23 UTC, jeeyyy commented on build/taskforce-rule-page/get-acknowledgements.js
> +	const acknowledgements = frontmatter.acknowledgments || frontmatter.acknowledgements
There is a test now which catches the spelling of `acknowledgments`. So this can be removed.

2020-10-13 14:59 UTC, WilcoFiers commented on build/taskforce-rule-page/get-reference-links.js
> +	const firstDfn = markdownAST.children.find(({ type }) => type === 'definition')
You want me to pull in a dependency to replace 1 line of code? That seems unnecessary.

2020-10-13 14:59 UTC, WilcoFiers commented on build/taskforce-rule-page/get-rule-metadata.js
> +		'Last Modified:\n' + toDfnTerm('TODO (format Sep 25, 2019)'),
Jup

2020-10-13 14:59 UTC, WilcoFiers commented on build/taskforce-rule-page/get-acknowledgements.js
> +	const acknowledgements = frontmatter.acknowledgments || frontmatter.acknowledgements
Doesn't hurt to be careful.

2020-10-13 14:59 UTC, WilcoFiers commented on build/__test-utils.js
> +	const title = term[0].toUpperCase() + term.substr(1)
Object keys are always a string. If somehow it isn't, or if somehow this is an empty string, It definitely should throw, which it does.

2020-10-13 14:59 UTC, WilcoFiers commented on build/taskforce-markdown.js
> +		if (ruleIds.length && !ruleIds.includes(ruleData.frontmatter.id)) {
Why would doing the same loop twice improve readability? I don't think I agree with you on that.

2020-10-13 14:59 UTC, WilcoFiers commented on build/taskforce-rule-page/get-rule-metadata.js
> +	const indentedLines = lines.map((line, index) => (index === 0 ? `:   ${line}` : `    ${line}`))
I think you'll survive having to distinguish a thing with 3 spaces from a thing with 4.

2020-10-13 15:18 UTC, jeeyyy commented on build/taskforce-rule-page/get-rule-metadata.js
> +	const indentedLines = lines.map((line, index) => (index === 0 ? `:   ${line}` : `    ${line}`))
Well I had difficulty, hence the comment.

2020-10-13 15:20 UTC, jeeyyy commented on build/taskforce-rule-page/get-reference-links.js
> +	const firstDfn = markdownAST.children.find(({ type }) => type === 'definition')
No need to pull in any dependency. There is already a helper fn as pointed out. I personally have hit undefined sometime when using `markdownAST.children` hence the suggestion. But will leave it up to you.

2020-10-13 15:21 UTC, jeeyyy commented on build/taskforce-rule-page/get-acknowledgements.js
> +	const acknowledgements = frontmatter.acknowledgments || frontmatter.acknowledgements
Redundant code. We ensure we get that spelling right and changed all usages. Nothing to be careful about here.

2020-10-14 12:33 UTC, jeeyyy approved these changes

2021-06-02 12:55 UTC, merged