fix: parse and render recursive glossary references
act-rules/act-rules-web pull request #209
Opened 2020-09-20 18:14 UTC by jeeyyy

This PR, enhances the glossary look up script to parse glossary referred not only in the markdown content of the rules page, but also in the glossary markdown content itself, to ensure recursive references are parsed and rendered correctly.

Also refactored the glossary rendering section of a rule page to be a component & added some styles so that there is clearer distinction between between each sections.

Example screenshot:
![image](https://user-images.githubusercontent.com/20978252/93718642-6efc5f00-fb75-11ea-9c12-b65c1d58a5eb.png)

Closes:
- https://github.com/act-rules/act-rules-web/issues/23

2020-09-21 07:18 UTC, Jym77 requested changes

2020-09-21 07:18 UTC, Jym77 commented on build/create-glossary-usages.js
> +}
🤔 I think this could directly update the glossary usage in rule. That would avoid having 2 structures to pass around, and separate better the building of data (here) with the rendering (simplifying `getGlossaryKeyForRule`).

Currently, we build 2 maps:
* `glossaryUsedInRules` maps definitions key to the slugs of the rules using that definition.
* `glossaryUsedInGlossary` maps definitions key to the keys of other definitions used into it.

Then, during rendering, these two maps are merged together, but the merging is redone for every rule and definition we render.
Additionally, the semantics of these maps is slightly different ("key -> rule **using it**" vs "key => definitions **used in it**") making it a bit annoying to remember the differences.


---
I would suggest instead to have `getGlossaryReferencedInGlossary` updating `glossaryUsedInRules` directly. So essentially, if definition with key `key` is calling definitions with links `[link1, link2, …]` we just need to do something like `glossaryUsedInRules[link1].concat(glossaryUsedInRules[key])` (+ checking unicity), and the full usage in rule is already done.

Using sets instead of arrays will take care of the unicity for you (also when initially building `glossaryUsedInRules`, i.e. simplifying https://github.com/act-rules/act-rules-web/pull/209/files#diff-1ee806e039039468cfa42dffe903198bR70-R74 ) and since sets can be iterated, shouldn't change the usage during rendering that much.

---
Given that we actually need the mapping in both directions ("def -> rules using it" and "rules -> defs used in it"), we should probably build both at the same time instead of only building one and reversing it (many times) during rendering.

So:
1. at the same time that we do `glossaryUsedInRules[key].push(usage)`, we can also do `rulesUsingDefinition[slug].push(key)`.
2. when processing definition and doing `glossaryUsedInRules[link1].concat(glossaryUsedInRules[key])`, we need to add `for (const {slug} of glossaryUsedInRules[key]) {rulesUsingDefinition[slug].push(link1) }`
3. take the opportunity to push `#outcome` everywhere at that point, so that rendering doesn't care about this.

Again, using sets will remove the need for checking unicity ourselves.

2020-09-21 23:55 UTC, jeeyyy commented on .github/workflows/build.yml
> +          node-version: '12'
Using [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) which needs Node >= v12

2020-09-22 07:38 UTC, Jym77 approved these changes

2020-09-22 13:14 UTC, merged