Add IBM to implementations
act-rules/act-rules-web pull request #258
Opened 2022-02-17 13:26 UTC by WilcoFiers

2022-02-17 14:20 UTC, carlosapaduarte requested changes
Editorial

2022-02-17 14:20 UTC, carlosapaduarte commented on README.md
> +Check that the script does not error, and that a the a file is created for the new implementation in `_data/implementations/`. If an error occurs, this is most likely due because of an issue in the E
```suggestion
Check that the script does not return any error, and that a file is created for the new implementation in `_data/implementations/`. If an error occurs, this is most likely due because of an issue in the EARL+JSON format.
```

2022-02-17 17:42 UTC, carlosapaduarte approved these changes

2022-02-18 10:28 UTC, Jym77 approved these changes
Mostly changes to the process writing; could be pushed to another PR if we want the IBM data to start showing 😃

2022-02-18 10:28 UTC, Jym77 commented on README.md
> +When using a GitHub repository, a raw GitHub URL can be used. When using a GitHub URL, make sure to use one that includes a branch name so that the URL won't need to be updated when the report is upd
```suggestion
When using a GitHub repository, a raw GitHub URL can be used. When using a GitHub URL, make sure to use one that includes a branch name so that the URL won't need to be updated when the report is updated. An example of such a URL is the following, used by QualWeb: `https://raw.githubusercontent.com/act-rules/act-rules-implementation-qualweb/master/reports/qualweb-report.json`
```

2022-02-18 10:28 UTC, Jym77 commented on README.md
> +In the root of this repository is the `implementations.yml` file. This file contains a list of all implementations on the ACT Rules website. To add an implementation, copy an existing implementation
Is this a step anybody can do? Or only people with write access to this repo ("Request a chair to edit the file…")? Or should they open a PR to make the edit?

Also, we're already in a "how to add an implementation" section, so maybe no need to repeat it + we can likn to the file directly.
```suggestion
### Step 2: Update `implementations.yml`

On a local branch, edit the [`implementations.yml`](./implementations.yml) file in the root of this repository; it contains a list of all implementations on the ACT Rules website. Copy an existing implementation and adjust the properties as needed. The `description` property is optional, although we strongly recommend providing this too.
```
(also, we should probably say "file in the fields `foo`, `bar`, …" with their meaning and only conclude "you can do that by copying existing data" rather than say to copy and edit, but that's likely a different topic)

2022-02-18 10:28 UTC, Jym77 commented on README.md
> +Create a pull request including the changes to `implementations.yml` and request a review from one of the ACT-Rules chairs. Once merged, the new integration will be published the next time the publis
Can/should we auto-assign some people to any PR in this repo?

2022-02-18 16:03 UTC, merged